return {
  ["null-ls"] = "",
  ["rust-analyzer"] = "󱘗",
  ansiblels = "󱂚",
  basedpyright = "󰌠",
  clangd = "",
  copilot = "",
  docker_compose_language_service = "",
  dockerls = "󰡨",
  gopls = "",
  jsonls = "",
  lua_ls = "󰢱",
  marksman = "",
  neocmake = "",
  pylsp = "󰌠",
  ruff_lsp = "󱔎",
  taplo = "",
  tsserver = "󰛦",
  typos_lsp = "",
  yamlls = "",
}
